//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDocumentProcessor.Web.ApplicationLogic.Proxies.FileService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NeonFSDataColumnBuilder", Namespace = "http://schemas.datacontract.org/2004/07/Neon.ISG.FileServices.DataContracts")]
    public partial class NeonFSDataColumnBuilder : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool AllowDBNullField;

        private string ColumnNameField;

        private string DataTypeNameField;

        private string DefaultValueStringField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowDBNull
        {
            get
            {
                return this.AllowDBNullField;
            }
            set
            {
                this.AllowDBNullField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnName
        {
            get
            {
                return this.ColumnNameField;
            }
            set
            {
                this.ColumnNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataTypeName
        {
            get
            {
                return this.DataTypeNameField;
            }
            set
            {
                this.DataTypeNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultValueString
        {
            get
            {
                return this.DefaultValueStringField;
            }
            set
            {
                this.DefaultValueStringField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NeonFSDataTableMetaData", Namespace = "http://schemas.datacontract.org/2004/07/Neon.ISG.FileServices.DataContracts")]
    public partial class NeonFSDataTableMetaData : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Collections.Generic.List<NeonFSDataTableColumn> ColumnsField;

        private NeonFSISGDatabaseType DatabaseTypeField;

        private NeonFSDataTableMetaData MetaDataField;

        private string NameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<NeonFSDataTableColumn> Columns
        {
            get
            {
                return this.ColumnsField;
            }
            set
            {
                this.ColumnsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public NeonFSISGDatabaseType DatabaseType
        {
            get
            {
                return this.DatabaseTypeField;
            }
            set
            {
                this.DatabaseTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public NeonFSDataTableMetaData MetaData
        {
            get
            {
                return this.MetaDataField;
            }
            set
            {
                this.MetaDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NeonFSDataTableColumn", Namespace = "http://schemas.datacontract.org/2004/07/Neon.ISG.FileServices.DataContracts")]
    public partial class NeonFSDataTableColumn : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Nullable<short> ColumnOrdinalField;

        private string ExcelColumnField;

        private string FriendlyNameField;

        private bool IsNullableField;

        private bool IsPrimaryKeyField;

        private bool IsReadonlyIdentityField;

        private short LengthField;

        private string NameField;

        private string ParentSourceTableField;

        private string ParentTableField;

        private System.Nullable<short> PrecisionField;

        private System.Nullable<int> ScaleField;

        private string StrongTypeNameField;

        private string TypeNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> ColumnOrdinal
        {
            get
            {
                return this.ColumnOrdinalField;
            }
            set
            {
                this.ColumnOrdinalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExcelColumn
        {
            get
            {
                return this.ExcelColumnField;
            }
            set
            {
                this.ExcelColumnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyName
        {
            get
            {
                return this.FriendlyNameField;
            }
            set
            {
                this.FriendlyNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNullable
        {
            get
            {
                return this.IsNullableField;
            }
            set
            {
                this.IsNullableField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrimaryKey
        {
            get
            {
                return this.IsPrimaryKeyField;
            }
            set
            {
                this.IsPrimaryKeyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReadonlyIdentity
        {
            get
            {
                return this.IsReadonlyIdentityField;
            }
            set
            {
                this.IsReadonlyIdentityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Length
        {
            get
            {
                return this.LengthField;
            }
            set
            {
                this.LengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentSourceTable
        {
            get
            {
                return this.ParentSourceTableField;
            }
            set
            {
                this.ParentSourceTableField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentTable
        {
            get
            {
                return this.ParentTableField;
            }
            set
            {
                this.ParentTableField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Precision
        {
            get
            {
                return this.PrecisionField;
            }
            set
            {
                this.PrecisionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Scale
        {
            get
            {
                return this.ScaleField;
            }
            set
            {
                this.ScaleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrongTypeName
        {
            get
            {
                return this.StrongTypeNameField;
            }
            set
            {
                this.StrongTypeNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName
        {
            get
            {
                return this.TypeNameField;
            }
            set
            {
                this.TypeNameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NeonFSISGDatabaseType", Namespace = "http://schemas.datacontract.org/2004/07/Neon.ISG.FileServices.DataContracts")]
    public enum NeonFSISGDatabaseType : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISGAdmin = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISGClient = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISGInput = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISGOutput = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISGTransient = 4,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NeonFSUniverse", Namespace = "http://schemas.datacontract.org/2004/07/Neon.ISG.FileServices.DataContracts")]
    public partial class NeonFSUniverse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Collections.Generic.List<NeonFSUniverseMap> UniverseMapsField;

        private string UniverseNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<NeonFSUniverseMap> UniverseMaps
        {
            get
            {
                return this.UniverseMapsField;
            }
            set
            {
                this.UniverseMapsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniverseName
        {
            get
            {
                return this.UniverseNameField;
            }
            set
            {
                this.UniverseNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NeonFSUniverseMap", Namespace = "http://schemas.datacontract.org/2004/07/Neon.ISG.FileServices.DataContracts")]
    public partial class NeonFSUniverseMap : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string InputTableField;

        private NeonFSISGDatabaseType LoadISGDatabaseField;

        private bool QuarterInNameField;

        private string UniverseTemplateKeyField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InputTable
        {
            get
            {
                return this.InputTableField;
            }
            set
            {
                this.InputTableField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public NeonFSISGDatabaseType LoadISGDatabase
        {
            get
            {
                return this.LoadISGDatabaseField;
            }
            set
            {
                this.LoadISGDatabaseField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool QuarterInName
        {
            get
            {
                return this.QuarterInNameField;
            }
            set
            {
                this.QuarterInNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniverseTemplateKey
        {
            get
            {
                return this.UniverseTemplateKeyField;
            }
            set
            {
                this.UniverseTemplateKeyField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "INeonISGFileService")]
    public interface INeonISGFileService
    {

        // CODEGEN: Generating message contract since the wrapper namespace (http//isgfileservices.com/UniverseFileService) of message UniverseFileUpload does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/INeonISGFileService/UploadUniverseFile")]
        void UploadUniverseFile(UniverseFileUpload request);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/INeonISGFileService/UploadUniverseFile")]
        System.Threading.Tasks.Task UploadUniverseFileAsync(UniverseFileUpload request);

        // CODEGEN: Generating message contract since the wrapper namespace (http//isgfileservices.com/ClientFileService) of message ClientChangeFileUpload does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/INeonISGFileService/UploadClientChangeFile")]
        void UploadClientChangeFile(ClientChangeFileUpload request);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/INeonISGFileService/UploadClientChangeFile")]
        System.Threading.Tasks.Task UploadClientChangeFileAsync(ClientChangeFileUpload request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UniverseFileUpload", WrapperNamespace = "http//isgfileservices.com/UniverseFileService", IsWrapped = true)]
    public partial class UniverseFileUpload
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http//isgfileservices.com/UniverseFileService")]
        public System.Collections.Generic.List<NeonFSDataColumnBuilder> ExtraColumns;

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http//isgfileservices.com/UniverseFileService")]
        public string FileName;

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http//isgfileservices.com/UniverseFileService")]
        public System.Collections.Generic.List<NeonFSDataTableMetaData> MetaData;

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http//isgfileservices.com/UniverseFileService")]
        public NeonFSUniverse Universe;

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http//isgfileservices.com/UniverseFileService")]
        public string UploadCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http//isgfileservices.com/UniverseFileService", Order = 0)]
        public System.IO.Stream UniverseFile;

        public UniverseFileUpload()
        {
        }

        public UniverseFileUpload(System.Collections.Generic.List<NeonFSDataColumnBuilder> ExtraColumns, string FileName, System.Collections.Generic.List<NeonFSDataTableMetaData> MetaData, NeonFSUniverse Universe, string UploadCode, System.IO.Stream UniverseFile)
        {
            this.ExtraColumns = ExtraColumns;
            this.FileName = FileName;
            this.MetaData = MetaData;
            this.Universe = Universe;
            this.UploadCode = UploadCode;
            this.UniverseFile = UniverseFile;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ClientChangeFileUpload", WrapperNamespace = "http//isgfileservices.com/ClientFileService", IsWrapped = true)]
    public partial class ClientChangeFileUpload
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http//isgfileservices.com/ClientFileService")]
        public System.Collections.Generic.List<NeonFSDataColumnBuilder> ExtraColumns;

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http//isgfileservices.com/ClientFileService")]
        public string FileName;

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http//isgfileservices.com/ClientFileService")]
        public NeonFSDataTableMetaData MetaData;

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http//isgfileservices.com/ClientFileService")]
        public string SheetName;

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http//isgfileservices.com/ClientFileService")]
        public string UploadCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http//isgfileservices.com/ClientFileService", Order = 0)]
        public System.IO.Stream ClientChangeFile;

        public ClientChangeFileUpload()
        {
        }

        public ClientChangeFileUpload(System.Collections.Generic.List<NeonFSDataColumnBuilder> ExtraColumns, string FileName, NeonFSDataTableMetaData MetaData, string SheetName, string UploadCode, System.IO.Stream ClientChangeFile)
        {
            this.ExtraColumns = ExtraColumns;
            this.FileName = FileName;
            this.MetaData = MetaData;
            this.SheetName = SheetName;
            this.UploadCode = UploadCode;
            this.ClientChangeFile = ClientChangeFile;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INeonISGFileServiceChannel : INeonISGFileService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NeonISGFileServiceClient : System.ServiceModel.ClientBase<INeonISGFileService>, INeonISGFileService
    {

        public NeonISGFileServiceClient()
        {
        }

        public NeonISGFileServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public NeonISGFileServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public NeonISGFileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public NeonISGFileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void INeonISGFileService.UploadUniverseFile(UniverseFileUpload request)
        {
            base.Channel.UploadUniverseFile(request);
        }

        public void UploadUniverseFile(System.Collections.Generic.List<NeonFSDataColumnBuilder> ExtraColumns, string FileName, System.Collections.Generic.List<NeonFSDataTableMetaData> MetaData, NeonFSUniverse Universe, string UploadCode, System.IO.Stream UniverseFile)
        {
            UniverseFileUpload inValue = new UniverseFileUpload();
            inValue.ExtraColumns = ExtraColumns;
            inValue.FileName = FileName;
            inValue.MetaData = MetaData;
            inValue.Universe = Universe;
            inValue.UploadCode = UploadCode;
            inValue.UniverseFile = UniverseFile;
            ((INeonISGFileService)(this)).UploadUniverseFile(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task INeonISGFileService.UploadUniverseFileAsync(UniverseFileUpload request)
        {
            return base.Channel.UploadUniverseFileAsync(request);
        }

        public System.Threading.Tasks.Task UploadUniverseFileAsync(System.Collections.Generic.List<NeonFSDataColumnBuilder> ExtraColumns, string FileName, System.Collections.Generic.List<NeonFSDataTableMetaData> MetaData, NeonFSUniverse Universe, string UploadCode, System.IO.Stream UniverseFile)
        {
            UniverseFileUpload inValue = new UniverseFileUpload();
            inValue.ExtraColumns = ExtraColumns;
            inValue.FileName = FileName;
            inValue.MetaData = MetaData;
            inValue.Universe = Universe;
            inValue.UploadCode = UploadCode;
            inValue.UniverseFile = UniverseFile;
            return ((INeonISGFileService)(this)).UploadUniverseFileAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void INeonISGFileService.UploadClientChangeFile(ClientChangeFileUpload request)
        {
            base.Channel.UploadClientChangeFile(request);
        }

        public void UploadClientChangeFile(System.Collections.Generic.List<NeonFSDataColumnBuilder> ExtraColumns, string FileName, NeonFSDataTableMetaData MetaData, string SheetName, string UploadCode, System.IO.Stream ClientChangeFile)
        {
            ClientChangeFileUpload inValue = new ClientChangeFileUpload();
            inValue.ExtraColumns = ExtraColumns;
            inValue.FileName = FileName;
            inValue.MetaData = MetaData;
            inValue.SheetName = SheetName;
            inValue.UploadCode = UploadCode;
            inValue.ClientChangeFile = ClientChangeFile;
            ((INeonISGFileService)(this)).UploadClientChangeFile(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task INeonISGFileService.UploadClientChangeFileAsync(ClientChangeFileUpload request)
        {
            return base.Channel.UploadClientChangeFileAsync(request);
        }

        public System.Threading.Tasks.Task UploadClientChangeFileAsync(System.Collections.Generic.List<NeonFSDataColumnBuilder> ExtraColumns, string FileName, NeonFSDataTableMetaData MetaData, string SheetName, string UploadCode, System.IO.Stream ClientChangeFile)
        {
            ClientChangeFileUpload inValue = new ClientChangeFileUpload();
            inValue.ExtraColumns = ExtraColumns;
            inValue.FileName = FileName;
            inValue.MetaData = MetaData;
            inValue.SheetName = SheetName;
            inValue.UploadCode = UploadCode;
            inValue.ClientChangeFile = ClientChangeFile;
            return ((INeonISGFileService)(this)).UploadClientChangeFileAsync(inValue);
        }
    }

}

