//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDocumentProcessor.Data.Entities.SystemGenerated
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientInformation
    {
        public int client_id { get; set; }
        public int client_key { get; set; }
        public string client_name { get; set; }
        public string record_status { get; set; }
        public System.DateTime create_dt { get; set; }
        public string create_by { get; set; }
        public System.DateTime modify_dt { get; set; }
        public string modify_by { get; set; }
        public string inputTable { get; set; }
        public string outputTable { get; set; }
        public string transientTable { get; set; }
    }
}
