//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDocumentProcessor.Data.Entities.SystemGenerated
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelValidationRecord
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string ExcelSheet { get; set; }
        public string ExcelColumn { get; set; }
        public Nullable<int> MaxStringLength { get; set; }
        public Nullable<int> ExcelRow { get; set; }
        public int ValidationErrorResultTypeId { get; set; }
        public Nullable<int> ValidationErrorDataTypeId { get; set; }
        public string Message { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string FileName { get; set; }
        public string BadValue { get; set; }
    
        public virtual ExcelValidationDataType ExcelValidationDataType { get; set; }
        public virtual ExcelValidationResultType ExcelValidationResultType { get; set; }
    }
}
