//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDocumentProcessor.Data.Entities.SystemGenerated
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelValidationResultType
    {
        public ExcelValidationResultType()
        {
            this.ExcelValidationRecords = new HashSet<ExcelValidationRecord>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ExcelValidationRecord> ExcelValidationRecords { get; set; }
    }
}
