//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDocumentProcessor.Data.Entities.SystemGenerated
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISGAdminEntities : DbContext
    {
        public ISGAdminEntities()
            : base("name=ISGAdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ExcelValidationDataType> ExcelValidationDataTypes { get; set; }
        public DbSet<ExcelValidationRecord> ExcelValidationRecords { get; set; }
        public DbSet<ExcelValidationResultType> ExcelValidationResultTypes { get; set; }
        public DbSet<Function> Functions { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RoleAssignment> RoleAssignments { get; set; }
        public DbSet<RoleMapping> RoleMappings { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<YearQuater> YearQuaters { get; set; }
    }
}
