//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDocumentProcessor.Web.ApplicationLogic.Entities.SystemGenerated
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBTable
    {
        public DBTable()
        {
            this.ExcelDBTableColumnMaps = new HashSet<ExcelDBTableColumnMap>();
            this.GridColumnConfigs = new HashSet<GridColumnConfig>();
            this.FundTypeMaps = new HashSet<FundTypeMap>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ExcelDBTableColumnMap> ExcelDBTableColumnMaps { get; set; }
        public virtual ICollection<GridColumnConfig> GridColumnConfigs { get; set; }
        public virtual ICollection<FundTypeMap> FundTypeMaps { get; set; }
    }
}
