//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDocumentProcessor.Web.ApplicationLogic.Entities.SystemGenerated
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelDBTableColumnMap
    {
        public long Id { get; set; }
        public long ISGDBId { get; set; }
        public string DBTableColumnName { get; set; }
        public string ExcelColumnName { get; set; }
        public long DBTableId { get; set; }
    
        public virtual DBTable DBTable { get; set; }
        public virtual ISGDB ISGDB { get; set; }
    }
}
