//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDocumentProcessor.Web.ApplicationLogic.Entities.SystemGenerated
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundTypeMap
    {
        public long Id { get; set; }
        public Nullable<long> FundTypeId { get; set; }
        public Nullable<long> FundTypeTemplateKeyId { get; set; }
        public Nullable<long> DBTableId { get; set; }
        public Nullable<long> LoadISGDBId { get; set; }
    
        public virtual DBTable DBTable { get; set; }
        public virtual FundType FundType { get; set; }
        public virtual FundTypeTemplateKey FundTypeTemplateKey { get; set; }
        public virtual ISGDB ISGDB { get; set; }
    }
}
