//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDocumentProcessor.Web.ApplicationLogic.Entities.SystemGenerated
{
    using System;
    using System.Collections.Generic;
    
    public partial class GridColumnConfig
    {
        public long Id { get; set; }
        public long DBTableId { get; set; }
        public string FriendlyName { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public Nullable<long> Order { get; set; }
        public Nullable<long> Width { get; set; }
        public Nullable<bool> Sortable { get; set; }
        public Nullable<bool> Editable { get; set; }
        public Nullable<long> SearchTypeId { get; set; }
        public Nullable<bool> Frozen { get; set; }
        public long ISGDBId { get; set; }
        public string DBTableColumnName { get; set; }
    
        public virtual DBTable DBTable { get; set; }
        public virtual ISGDB ISGDB { get; set; }
        public virtual SearchType SearchType { get; set; }
    }
}
