//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDocumentProcessor.Web.ApplicationLogic.Entities.SystemGenerated
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchType
    {
        public SearchType()
        {
            this.GridColumnConfigs = new HashSet<GridColumnConfig>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<GridColumnConfig> GridColumnConfigs { get; set; }
    }
}
