//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDocumentProcessor.Web.ApplicationLogic.Entities.SystemGenerated
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UIConfigEntities : DbContext
    {
        public UIConfigEntities()
            : base("name=UIConfigEntities")
        {
        }

        public UIConfigEntities(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DBTable> DBTables { get; set; }
        public DbSet<ExcelDBTableColumnMap> ExcelDBTableColumnMaps { get; set; }
        public DbSet<GridColumnConfig> GridColumnConfigs { get; set; }
        public DbSet<ISGDB> ISGDBs { get; set; }
        public DbSet<SearchType> SearchTypes { get; set; }
        public DbSet<FundType> FundTypes { get; set; }
        public DbSet<FundTypeMap> FundTypeMaps { get; set; }
        public DbSet<FundTypeTemplateKey> FundTypeTemplateKeys { get; set; }
    }
}
